label.py: Fix Label when initial text is not provided
This change addresses cases when Label class is initialized with
max_glyphs instead of text. In such cases, the split function is
attempted on None object instead of an empty string:

  File "/lib/adafruit_display_text/label.py", line 84, in __init__
  AttributeError: 'NoneType' object has no attribute 'split'

Fixes: https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/141